# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Vinicius Guerra e Ribas
# Description of the Site
description: Portfolio & Repository
# URL of Image of the Site
site-image: https://repository-images.githubusercontent.com/433614529/072cf448-105f-491a-9dad-c5d41358f599
# Keywords of the Site
site-keywords: Site, Portfolio, Vinicius Guerra e Ribas , Repository, Projects
# URL for the Image of custom Favicon
favicon-url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAIY0lEQVR4nO2dPW6lQAzHfYSUlHuEcIMUHCAl5XacgD7iAJOWbiXqSGmoSUn5JHqUI+QIs8V7PL0QxuP5AEOekX7NKpkY/B+Pxx5YAPv1CAAvAPABACcA+AIALeyWTwB4v/js8Yc3Ha4nODuc+4aEME4A8BccrgcA+LcDw4W4/APC9QDn8MFtrLAOp4uPF68HOK/z3EYK6/IJhut1B8YJ2/ABs+tpB0YJ2/IMN9fHDgwStuUTLtfjDowRePgDcC4YcBsi8PACINu+e+YEcF4LuA0RePgCEAHcO+wGCCIAgRF2AwQRgMAIuwGCCEBghN0AQQQgMMJugCACEBhhN0AQAQiMsBsgiAAERtgNEEQAAiPsBggiAIERdgMEEYDACLsBd0+SJLosS13XtW7bVg/DoMdxvDIMg27bViuldJqmIoDfQlmW+u3t7ZuzKbRtG1MI/A/i3ijLUvd97+z4eVTIskwEcCTyPNdd1wU5fh4JRACMpGmqm6bRbdvqpml0nufGn22aJprjbzmcALIs03mer5HMbM7S+l2W5befSZLE2flT0jcxTwoPK4D5g4iczGxKmqZG5906nxryh2HQdV0vrutKqeMLIM9z440nSbL630+SRBdFoZVS32ZXXddR72ccR53nuc6yjOT8YRi0Ugp9BqYI0nXdcQSAqXgeNmNC2Wr5/H1MAE3ToGHbNQKadgy+4v3GViG4rutNBUCdgeM46qqqnMc3LQHUcE/9m0VRGMcpiiL8Wa09AycwZ8ReArIsI83AKYz6/n0f53dd57R/b9vWKKIoz2saMFJRYRFstkRax5yc3/e9bpomeAa5Or9pGiexYbM/Svi/FUBsR9xSluX6N0JwfuxauovzlVJOYydJglYLo91HiJFUsH1wlHXM4vxhGNAizdoC8FlisZypaZp49zF/UGtsyVYuZOg0TVHnr7W82Rzv+7ex0B/dR6uqC84z03QzMWrZWLGl7/vVnG/bBfg637aMxYqYRgGMY9yEENv/hy45NuevWWAyZechzs/z3JrDRL+XtWbmBLb9CxEa5vw1w75N1D7PL0kSdM1fIzKjAogVapIkQWfJEZ1PKQC5CCDPc+vZgNWcjwmg7/vgwbFk5u3tzXtcLPxGXyNn2GY/VQCUWT+OGxTpsDp56JqDbf98yq8A+PbId8ytBZBlmXXWrx3Jrti2UCEFB+wGfcbFGjAhEcUF7HlRBEAV0BYd0gu4Ub4PFnOWz/KCVcZiZPxpml47h8Mw6L7vjREwyzI0ui0JgNqcWqsYhwoAwNxy9F1XY1eysKUqJFSWZYnmFJitpokzFwBl1q9VrSQLwDZjXWcYpnbXxAazzWfGpGmqlVKkjiHWq7Cd1KHO+pCOZDQB2GaZS9MG2/6No1v7Fwv91AZWmqY6z3Pnc/i2RAxrclHPAcZshgULwJbgUEMttv1z7Tpis2zJnjRNr2/YUB1tstN2v1hkoohr7S2rswBsD5zqPEz9rpHEJMil0B/iENvYMQXQdd2eDsP+/EcsIaQ8nFgJpUmMppyEkmxRoNroI4AdhHy7AGw3hoVGW6nUxTjT7DcVfGIJYI0IMAzDJkfvoggAAE8IsaUAS4xcauTYOKbwaTtFQ4VaUaQKwPUc4C4EYEsITbMEE45LqdY0ji0PSZJEV1X17Y2a6U2buq5JUYK6H6eM1XWdLopC53nOudVzFwDlBpdUHWMXgW0jQ+v9lO1ZTAHYxDF/SUUpdWUSzsRKAsJ/AAup82QMO/3j0v71Cf8UqGf5qULF7NyCSALCb9K2zt1mtVVVGX/OpadgmqWhDR9qcYY6HrZNPQKXnMx+o7bq2TQrsZ9zyYBNUSck/Ltk7C7jUnr6e4YkAFtCOGX3FJFQMI0R0iyhVgZdj3PF2nruWgCUG8WaHi7tX2ym+jofK02HCgBb9uZrtAsxvyQSRQCAhGYbLu3f2AJwXaddBbCGYG33c5vYTa+8K6WuPRDbRyW8BeBb+3Yp/8Z+oK5r9N4F4Mr0RZaqqq7fRriNLk4CALAnhEu47F9jPlDTWF3XGaOZqwCwrS/TAQ8yF7+4/RLlTNz8Ycdwmo8AltbR6ZyjKSn0eSfiqAK44P5LLpmvT/fLNJbLVtJk41TC3kIAO+n3xxcAAD0h9OmAmQo21KNpWFietqNbCIDhgOd2AqAmhL7vyJnGs1UDsbeGbn83pgBMY211VJ1FAAD4wU/fdXsCSzZNX9pIkgQt+NyuyabdQUwBxHzHcpcCsOUCIa+X2Xr7fd/rqqqu+2HbKd95LYJ6pDtEACET4BACsFXYQmeAy8eeMJYKUTEFsPKHHPcrANvx7xhJUKgITFVIUyvXJ2rdrQAA8DwgVhZsW9tdnQ8Qt95w1wLAmiGx98Eu39m3tY63qDjehQCwZstaByGLotBN0/wQw/T9P0rrGVu+XI9emaqjMb6xsHsBACyv00fYApkE4FPCXXrn/1dXAudM//GRUmqv599/YMpffB13+wwO4vx4AjgipsTyICVcEUAopuz9ICVcEUAoplpAtC9xHwN2A9jAuoY7fpVLBBATl9fPfynsBrBy8E6eCCAUUyVz1a9z7gt2A1gxHSCRHOCOmP5zx+n7gAcq4ogABBGAIAIQAmA3QBABCIywGyCIAARG2A0QRAACI+wGCCIAgRF2AwQRgMAIuwGCCEBghN0AQQQgMMJugCACEBiBrx0YITAK4LQDIwQePgEAPnZgiMDDCQDgdQeGCDy8AgA87MAQgYdnuFySB9wfn3BzPe3AIGFb/sLset+BUcI2vMPC9QCyFNwDp4uvFy8Rwe/mBAB/gHDJcvD7+ABk5i9dz3DOFLkNF8I4wULC53I9A8ALnBUkgtg3XxdOcC7yPIJl1v8HfXcuLGq8GmkAAAAASUVORK5CYII=


# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/7319189/pexels-photo-7319189.jpeg?w=1680&h=1120

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: viniciusgribas@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: https://www.linkedin.com/in/vinicius-guerra-e-ribas/
github_username: https://github.com/viniciusgribas
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: G-CKW158S8J3

# Disqus
disqus-shortname: viniciusgribas

# Name of the Author
author-name: viniciusgribas
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/viniciusgribas/portfolio/master/assets/images/perfil1.JPG?w=419&h=628
# 60 Words About the Author
author-about: Hello, how are you? I hope you are healthy and happy. My name is Vinicius. I'm an Energy Engineer and I'm doing a post-graduation in Data Science & Analitycs. Currently I work as an Eletrical Sector Analyst at Energisa.S.A., where I perform -principally- energy market analysis. I am passionate about data and I like to study the areas of technology, engineering, statistics, and sports. On this site I present some projects I have worked on, challenges in Kaggle, code and notes I like to keep. Hope you like it! Feel free to contact me.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/viniciusgribas

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "repository/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
